module:
  path: path
  packages:
    - name: client
      path: internal
      tags:
        - config
    - name: server
      path: internal/services
      tags:
        - config
        - service
      requires:
        - internal/client
