package templates

import "github.com/hjblom/fuse/internal/config"

type Interface interface {
	Generate(module string, com config.Component) error
}

func fileGeneratedDoNotEditHeader() string {
	return `Code generated by fuse. DO NOT EDIT.
`
}

func fileGeneratedSafeEditHeader() string {
	return `Code generated by fuse.
`
}
