components:
  - name: A
    requires:
      - B
      - F
  - name: B
    requires:
      - C
      - D
      - E
  - name: C
    requires:
      - E
  - name: D
    requires:
      - E
      - F
  - name: E
  - name: F
